### ISSUE TITLE
Fix exporting blobs

### ISSUE THREAD

**Issue by kevinychen** [kevinychen/snap2#32]
Currently anything that adds images to a spreadsheet does so using my normal user token, so it doesn't work except for publicly editable sheets or sheets shared with myself (but not sheets shared with the snap service account).

This is because images can't be added by a service account, as tracked [here](https://issuetracker.google.com/issues/36763096). Maybe as a workaround I can use a user account that isn't myself, but that user account needs to also be granted access to the Google Sheet. Or maybe there's a better workaround.

**Comment by cjquines** [comment]
thank you! i really appreciate this!
