### ISSUE TITLE
Join a puzzle tech Discord?

### ISSUE THREAD

**Issue by jenna-h** [kevinychen/snap2#62]
We're forming a Discord server, with the intent that people who work on puzzle tooling can ask each other questions and generally share knowledge; right now, the space is full of people solving similar problems as each other, over and over again.

I wasn't sure how to reach you, so I apologize for the blatant misuse of GitHub issues.

I'm jenna4234 on Discord; from there, I can invite you to the server. 

I sincerely hope you'll consider joining. I personally believe your tools are a great contribution to the community and I'm hoping you can get something out of discussion with others who are similarly enthusiastic.

**Comment by kevinychen** [comment]
That sounds cool. I'm kyc2915, both for Discord and Gmail.

P.S. as an unrelated aside, you've made me realize that my email address is already publicly visible in my Git commits
